person:
  userName: zhangsan
  boss: true
  birth: 2000/06/02
  age: 20
  pet:
    name: 番茄
    weight: 1
  interests:
    - 篮球
    - 足球
    - 游泳
  animal: [小猫,小狗,小鼠]
  score: {english: 80,math: 90}
#    - english: 80
#    - math: 90
  salarys:
    - 9999.98
    - 9999.99
  allPets:
    sick:
      - {name: 豆豆,age: 15}
      - {name: 小黑,age: 16}
    health:
      - {name: 番茄,age: 1}
      - {name: 小白,age: 1}
mycar:
  name: BYD
  price: 100000
#Spring相关配置
spring:
  datasource:
    url: jdbc:mysql://tx.mxlbs.cn:3306/nikki?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: nikki
    password: 2106739694
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      aop-patterns: com.nikki.boot.*  #监控SpringBean
      filters: stat,wall     # 底层开启功能，stat（sql监控），wall（防火墙）
      stat-view-servlet: # 配置监控页功能
        enabled: true
        login-username: admin
        login-password: admin0602
        resetEnable: false
      web-stat-filter: # 监控web
        enabled: true
        urlPattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      filter:
        stat: # 对上面filters里面的stat的详细配置
          slow-sql-millis: 1000
          logSlowSql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false
      max-active: 8 #最大连接池数量
      pool-prepared-statements: false
      max-wait: 6000 #连接等待超时的时间
      time-between-eviction-runs-millis: 2000 #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 600000 #配置一个连接在池中最小生存的时间，单位是毫秒
      max-evictable-idle-time-millis: 900000 #配置一个连接在池中最大生存的时间，单位是毫秒
      validation-query: select *
      test-while-idle: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    #开启参数方式的内容协商
    contentnegotiation:
      favor-parameter: true
  thymeleaf:
    prefix: classpath:/templates/
    mode: HTML
    cache: false
    encoding: UTF-8
    servlet:
      content-type: text/html
    suffix: .html
  #    static-path-pattern: /res/**
  resources:
    add-mappings: true
    cache:
      period: 11000
  banner:
    image:
      location: banner.jpg
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 20MB
server:
  servlet:
    encoding:
      force-request: true
  port: 21067

mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true